### ISSUE TITLE
Windows build failing

### ISSUE THREAD

**Issue by mjvk** [USNavalResearchLaboratory/protolib#18]
The new code introduced in protoFile.cpp at line 631:

```cpp
if (NULL == (current = new Directory(thePath)))
        {
            PLOG(PL_ERROR, "ProtoFile::DirectoryIterator::Open() new Directory error: %s\n", GetErrorString());
            return false;
        }
        current->dptr = NULL;
```

Tries to access dptr, dptr is not accessible on Windows.

```cpp
#ifdef WIN32
                HANDLE      hSearch;
#else  // UNIX
                DIR*        dptr;
#endif  // if/else WIN32/UNIX  
```

It might be nice to have a look at github actions so you can get informed of things like this automatically:
https://help.github.com/en/actions/building-and-testing-code-with-continuous-integration/setting-up-continuous-integration-using-github-actions

**Comment by bebopagogo** [comment]
OK ... i saw/reviewed/accept your continuous integration pull request.  I am taking a look at this Windows issue right now.

**Comment by bebopagogo** [comment]
I fixed this and _love_ the continuous integration addition.  Thanks very much for that!

**Comment by bebopagogo** [comment]
Also fixed the MinGW build issue via reports from the CI (very cool since I don't have my own MinGW build environment)

**Comment by mjvk** [comment]
Thanks for the fix and great to hear you like the CI!
