### ISSUE TITLE
protoPktIP:465 strange change => compile error

### ISSUE THREAD

**Issue by RocketRider** [USNavalResearchLaboratory/protolib#7]
I tried building NORM with the latest protolib and get the following error:
protoPktIP.cpp:465:14: error: case value evaluates to -1, which cannot be narrowed to type 'unsigned int' [-Wc++11-narrowing]
          case LENGTH_UNKNOWN:

I looked into the change and don't understand why you would change this. The switch is useless now. The new code seems incorrect:
https://github.com/USNavalResearchLaboratory/protolib/commit/cc94c5eae52b87c869ae28916e0dc61a215bba30

**Comment by bebopagogo** [comment]
This change was a mistake that crept in with a recent update to that IPv4 header option code.  Thanks catching this and reporting it.  I have fixed the issue.
